# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='pub_date',
        ),
    ]
