# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161101_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
