# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20161101_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Problem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
