# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20161101_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
