# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20161121_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
