# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20161122_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='problem_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
