# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20161122_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ranking',
            new_name='rating',
        ),
    ]
